#!/bin/zsh
set -euo pipefail

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                           Scripts"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setup & Configuration Commands:"
echo "  npm run setup                      - Install dependencies, configure profiles, and validate"
echo "  npm run sync                       - Apply Claude, Codex, and dotfiles from the repository"
echo "  npm run sync -- --force            - Apply all managed config regardless of timestamps"
echo "  npm run sync -- --only agents      - Apply Claude and Codex config only"
echo "  npm run sync -- --only claude      - Apply Claude config only"
echo "  npm run sync -- --only codex       - Apply Codex config only"
echo "  npm run sync -- --only dotfiles    - Apply dotfiles only"
echo "  npm run backup                     - Capture Claude and Codex config in the repository"
echo "  npm run backup -- --only claude    - Capture Claude config only"
echo "  npm run backup -- --only codex     - Capture Codex config only"
echo "  npm run rollback                   - Roll back to the most recent configuration snapshot"
echo "  npm run rollback -- <backup-dir>   - Roll back to a specific snapshot"
echo ""
echo "Advanced Tooling Repair Commands:"
echo "  npm run install:plugins        - Install Claude Code marketplaces and plugins"
echo "  npm run install:codex-plugins  - Install or refresh managed Codex plugins"
echo "  npm run install:codex-plugins -- --dry-run - Preview managed Codex plugin changes"
echo "  npm run install:agent-tooling  - Reconcile shared tooling and both native plugin sets"
echo "  npm run install:agent-tooling -- --dry-run - Preview complete agent tooling reconciliation"
echo "  npm run install:managed-tools - Reconcile all exact-pinned agent tools"
echo "  npm run install:managed-tools -- --dry-run - Check managed agent-tool drift"
echo "  npm run install:openwiki      - Install or update OpenWiki for agent documentation"
echo "  npm run install:openwiki -- --dry-run - Preview OpenWiki installation"
echo "  npm run install:plannotator    - Install or update the pinned Plannotator binary"
echo "  npm run install:plannotator -- --dry-run - Check the pinned Plannotator binary"
echo "  npm run install:skills         - Install, update, or safely prune shared git skills"
echo ""
echo "Update Commands:"
echo "  npm run update                 - Sync dotfiles/skills, then update dependencies"
echo "  npm run update -- --backup     - Capture agent config, then update"
echo "  npm run update -- --dry-run    - Preview updates without making changes"
echo "  npm run update -- --only <comp> - Update only brew, asdf, zsh, npm, or pip"
echo "  npm run update:tool-pins       - Check upstream releases against managed tool pins"
echo "  npm run update:tool-pins -- --apply - Update managed tool pins and checksums"
echo "  npm run update:asdf-pins       - Check upstream releases against asdf runtime pins"
echo "  npm run update:asdf-pins -- --apply - Update asdf runtime pins within their tracked lines"
echo ""
echo "Development Commands:"
echo "  npm run lint                   - ShellCheck, zsh syntax checks, and actionlint"
echo "  npm run scan:secrets           - Scan repository paths for likely secrets"
echo "  npm run audit:deps             - Fail on high/critical npm advisories"
echo "  npm test                       - Run all BATS tests"
echo "  bats tests/<suite>/*.bats      - Run a suite (claude, codex, utils, mac, update, setup, restore, meta)"
echo "  npm run test:watch             - Run tests continuously (uses nodemon)"
echo ""
echo "Release Commands:"
echo "  npm run version:show           - Print version, commit SHA, tag, and host"
echo "  npm run release -- <bump>      - Cut a release (patch|minor|major|x.y.z)"
echo "  npm run release -- --dry-run patch - Preview a release without changes"
echo ""
echo "Other Commands:"
echo "  npm run validate       - Check if all tools are properly installed"
echo "  npm run audit:agents   - Audit Codex config, plugins, MCP intent, skills, RTK, and CRG"
echo "  npm run audit:agents -- --repo-only - Deterministic tracked-config audit for CI"
echo "  npm run check:mcps     - Initialize every enabled base MCP server"
echo "  npm run check:mcps -- --profile apple          - Include native Xcode MCP"
echo "  npm run check:agent-tooling - Report shared capabilities and detect harness drift"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
