#!/bin/zsh
set -euo pipefail

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                           Scripts"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setup Commands:"
echo "  npm run setup          - Install dependencies, configure profiles, and validate"
echo ""
echo "Backup & Restore Commands:"
echo "  npm run restore:all            - Restore Claude Code, Codex, and dotfiles"
echo "  npm run restore:all -- --force - Force all managed config through one safe snapshot"
echo "  npm run restore:agents         - Restore Claude Code and Codex agent config"
echo "  npm run restore:claude         - Restore Claude Code config (only if repo is newer)"
echo "  npm run restore:claude -- --force - Force restore Claude Code config"
echo "  npm run restore:codex          - Restore Codex config (only if repo is newer)"
echo "  npm run restore:codex -- --force - Force restore Codex config"
echo "  npm run restore:dotfiles       - Copy dotfiles and reapply Worktrunk integration"
echo "  npm run backup:all             - Backup Claude Code and Codex config"
echo "  npm run backup:claude          - Backup Claude Code config to repository"
echo "  npm run backup:codex           - Backup Codex config to repository"
echo "  npm run install:plugins        - Install Claude Code marketplaces and plugins"
echo "  npm run install:codex-plugins  - Install or refresh managed Codex plugins"
echo "  npm run install:codex-plugins -- --dry-run - Preview managed Codex plugin changes"
echo "  npm run install:managed-tools - Reconcile all exact-pinned agent tools"
echo "  npm run install:managed-tools -- --dry-run - Check managed agent-tool drift"
echo "  npm run install:openwiki      - Install or update OpenWiki for agent documentation"
echo "  npm run install:openwiki -- --dry-run - Preview OpenWiki installation"
echo "  npm run install:plannotator    - Install or update the pinned Plannotator binary"
echo "  npm run install:plannotator -- --dry-run - Check the pinned Plannotator binary"
echo "  npm run install:skills         - Install, update, or safely prune shared git skills"
echo ""
echo "Update Commands:"
echo "  npm run update                 - Sync dotfiles/skills, then update dependencies"
echo "  npm run update:with-backup     - Capture live agent config, then run the safe update"
echo "  npm run update:tool-pins       - Check upstream releases against managed tool pins"
echo "  npm run update:tool-pins -- --apply - Update managed tool pins and checksums"
echo "  npm run update:asdf-pins       - Check upstream releases against asdf runtime pins"
echo "  npm run update:asdf-pins -- --apply - Update asdf runtime pins within their tracked lines"
echo "  npm run update:dry-run         - Preview updates without making changes"
echo "  npm run update:only -- <comp>  - Sync dotfiles/skills, then update one component"
echo ""
echo "Development Commands:"
echo "  npm run lint                   - ShellCheck, zsh syntax checks, and actionlint"
echo "  npm run scan:secrets           - Scan repository paths for likely secrets"
echo "  npm test                       - Run all BATS tests"
echo "  bats tests/<suite>/*.bats      - Run a suite (claude, codex, utils, mac, update, setup, restore, meta)"
echo "  npm run test:watch             - Run tests continuously (uses nodemon)"
echo ""
echo "Release Commands:"
echo "  npm run version:show           - Print version, commit SHA, tag, and host"
echo "  npm run release -- <bump>      - Cut a release (patch|minor|major|x.y.z)"
echo "  npm run release -- --dry-run patch - Preview a release without changes"
echo ""
echo "Other Commands:"
echo "  npm run validate       - Check if all tools are properly installed"
echo "  npm run audit:agents   - Audit Codex config, plugins, MCP intent, skills, RTK, and CRG"
echo "  npm run audit:agents -- --repo-only - Deterministic tracked-config audit for CI"
echo "  npm run check:mcps     - Initialize every enabled base MCP server"
echo "  npm run check:mcps -- --profile apple-headless - Include MCPs from a Codex profile"
echo "  npm run restore        - Restore from the most recent backup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
