#!/bin/zsh
set -euo pipefail

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                           Scripts"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setup Commands:"
echo "  npm run setup          - Install dependencies, configure profiles, and validate"
echo ""
echo "Backup & Restore Commands:"
echo "  npm run restore:all            - Restore Claude Code, Codex, and dotfiles"
echo "  npm run restore:agents         - Restore Claude Code and Codex agent config"
echo "  npm run restore:claude         - Restore Claude Code config (only if repo is newer)"
echo "  npm run restore:claude -- --force - Force restore Claude Code config"
echo "  npm run restore:codex          - Restore Codex config (only if repo is newer)"
echo "  npm run restore:codex -- --force - Force restore Codex config"
echo "  npm run restore:dotfiles       - Copy dotfiles to \$HOME"
echo "  npm run backup:all             - Backup Claude Code and Codex config"
echo "  npm run backup:claude          - Backup Claude Code config to repository"
echo "  npm run backup:codex           - Backup Codex config to repository"
echo "  npm run install:plugins        - Install Claude Code marketplaces and plugins"
echo "  npm run install:skills         - Clone/update git-based skills into Claude Code and Codex"
echo ""
echo "Update Commands:"
echo "  npm run update                 - Update all dependencies (includes Claude/Codex backup)"
echo "  npm run update:dry-run         - Preview updates without making changes"
echo "  npm run update:only -- <comp>  - Update only one component (brew, asdf, zsh, npm, pip)"
echo ""
echo "Development Commands:"
echo "  npm run lint                   - Run ShellCheck on all scripts"
echo "  npm run scan:secrets           - Scan repository paths for likely secrets"
echo "  npm test                       - Run all BATS tests"
echo "  bats tests/<suite>/*.bats      - Run a specific test suite (claude, utils, mac, update, setup)"
echo "  npm run test:watch             - Run tests continuously (uses nodemon)"
echo ""
echo "Release Commands:"
echo "  npm run version:show           - Print version, commit SHA, tag, and host"
echo "  npm run release -- <bump>      - Cut a release (patch|minor|major|x.y.z)"
echo "  npm run release -- --dry-run patch - Preview a release without changes"
echo ""
echo "Other Commands:"
echo "  npm run validate       - Check if all tools are properly installed"
echo "  npm run restore        - Restore from the most recent backup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
